expo/turtle

- .release-it.beta.json
- .release-it.json
- package.json
- yarn.lock
To automate releases.
`release-it` seems to be a nice tool to handle the release process. I created two configs - one for production releases and one for beta releases.
Production release:
- bumps version in `package.json`
- commits that change
- creates a git tag
- pushes the commit and the tag to the repository
- creates an entry on the Github Releases tab
- publishes the package to the npm (`latest` tag)
Beta release:
- bumps version in `package.json`
- doesn't commit that change (it's reverted at the end of the process)
- creates a git tag
- pushes the tag to the repository
- publishes the package to the npm (`beta` tag)
I tested the exact same configuration with a different package.
> use release-it to handle releases

- CHANGELOG.md
- src/jobManager.ts
- src/server.ts
- src/turtleContext.ts
Checking for reusable builds needs to have access to current turtle version and one available in npm is not always the same as on servers
The version is set under key `turtle:version`
> register turtle version in redis

- src/aws/cloudwatch/index.ts
- src/aws/sqs.ts
- src/bin/commands/setup.ts
- src/bin/index.ts
- src/bin/setup/utils/toolsDetector.ts
- src/bin/utils/builder.ts
- src/builders/utils/ios/keychain.ts
- src/jobManager.ts
- src/server.ts
- src/utils/priorities.ts
- src/utils/redis.ts
This makes log messages slightly easier to read in our monitoring dashboards, and also makes it slightly easier to search for or alert on particular errors.
[The bunyan log method api](https://github.com/trentm/node-bunyan#log-method-api) supports a few different ways of logging messages at a certain level. I preferred the last way - passing an object with an `err` field as the first argument - since it was more explicit, and makes it more obvious how to add more fields.
I would like there to be many more fields, for example it would be very good if all messages related to a particular build were tagged with the build's id, the app's slug, and the initiating user.  But that would be a broader change I won't prioritize right now.
I've checked the behavior of these arguments on the cli. For …
> Log error objects where possible

- .gitignore
- .ignore
- src/logger/gcloudStream.ts
- src/logger/index.ts
To make it easier to find logs in GCloud Console.
Basically, I copy-pasted `HackyLogglyStream` that we previously used in the project - https://github.com/expo/turtle/blob/de4837f36105c03be9afb4028241cff7459da974/src/logger/hackyLogglyStream.ts
Tested locally.
> record jobID and experience name in gcloud

- CHANGELOG.md
- Dockerfile
If possible, we'd like to get rid of a special kind of `package.json` only for Turtle environment.
If a tarball doesn't contain `universe-package.json`, install dependencies from the default `package.json` provided.
Created a simple 3 directories tree and ensured that this command should do what it's supposed to do. The following script:
```sh
for SDK_VERSION in `ls workingdir`; do \
cd ~/tmp/workingdir/$SDK_VERSION; \
if [ -f universe-package.json ]; then \
echo "universe" && echo $SDK_VERSION; \
else \
echo "expo" && echo $SDK_VERSION; \
fi \
; done
```
printed
```
expo
sdk30
universe
sdk31
expo
sdk32
```
for
```
workingdir
├── sdk30
├── sdk31
│   └── universe-package.json
└── sdk32
```
> Add support for Android tarballs without universe-package.json

- CHANGELOG.md
- shellTarballs/android/sdk32
We want to backport [fix](https://github.com/expo/expo/pull/4115) to SDK32.
> [android] Update shell tarball for SDK32 with AppAuth fixes

- src/bin/commands/build/android.ts
- src/builders/utils/android/credentials.ts
- src/job.ts
Fixes #64
When a user uses turtle-cli, and he wants to build for Android, and he doesn't provide the keystore for his app (by setting proper options and env variables) we fail to create one for him.
When we build for Android and we discover that a keystore doesn't exist we try to read Android package name from the app manifest. Unfortunately, the app manifest is not accessible for Turtle CLI builds, so I passed in another variable to job config and used that in Android credentials utils.
Tested locally.
> [turtle-cli] fix generating android keystore

- CHANGELOG.md
- shellTarballs/android/sdk33
- src/bin/setup/android/index.ts
- src/bin/setup/utils/common.ts
- src/builders/android.ts
#85, #86
- I changed the Android shell app for SDK33 to a one without node_modules in tools-public.
- From now on, `turtle-cli` will install dependencies for `tools-public` in shell apps only for SDK versions < 33.
- I fixed installing native modules when `manifest` is undefined.
> turtle-cli fixes for sdk 33

- CHANGELOG.md
- src/bin/commands/build/android.ts
- src/bin/commands/build/ios.ts
- src/bin/utils/builder.ts
- src/builders/android.ts
- src/builders/utils/common.ts
- src/builders/utils/ios/shellAppBuilder.ts
For turtle-cli builds manifest was fetched by xdl, so when unimodules were resolved it was not available
> fetch manifest in turtle-cli

- CHANGELOG.md
- package.json
- src/bin/setup/android/ndk.ts
- src/bin/setup/android/sdk.ts
- src/bin/setup/utils/common.ts
Upgrading shell apps is currently broken for users who use `turtle-cli`. During `setup:` phase we only check whether the shell app exists, we don't check its version.
After successfully setting up a shell app for a given platform and SDK version, I added creating a file in the shell app directory with the version of that shell app. Before each run of `turtle-cli` I check if the version is up-to-date and if it's not we remove the cached version from `~/.turtle` directory and download a new version from S3.
Tested locally.
> [turtle-cli] fix updating shell apps

- CHANGELOG.md
- src/builders/utils/version.ts
- src/server.ts
https://github.com/expo/universe/issues/3564
I added registering supported SDK versions (for a given platform) at the start of the server.
After starting the server I checked out that the `turtle:ios:sdkVersions` key has been set in Redis correctly.
> add registering supported sdk versions in redis

- CHANGELOG.md
- src/builders/utils/ios/adhocBuild.ts
- src/job.ts
- Allow the clients to specify a profile id for turtle to use
- the new `manage_adhoc_profile.rb` script should always return either a valid profile or error. Instead of detecting for empty credentials (which should no longer be the case), we check if the profile has been updated. If it has, we continue with the logic to save it on our servers, else we return.
https://github.com/expo/expo-cli/pull/700
https://github.com/expo/turtle/pull/88
https://github.com/expo/universe/pull/3573
> [turtle] use provisioiningProfileId if specified

- package.json
- yarn.lock
https://github.com/expo/turtle/pull/88 added support to use a `provisioningProfileId` in adhoc builds and we need the most recent version of travelling fastlane in order for it to work
> bump travelling fastlane

- CHANGELOG.md
- package.json
- src/builders/utils/android/credentials.ts
- yarn.lock
Fixes https://github.com/expo/turtle/issues/115
The fix was actually implemented in `@expo/xdl` - https://github.com/expo/expo-cli/pull/869/files
In the case of Android debug builds we need to set the `DEVELOPMENT_URL` constant to the app's manifest url in `app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java`. Otherwise, the app crashes immediately after running it on a phone.
> fix android debug builds

- .envrc
- .envrc.local.example
- .gitignore
- .release-it.json
- CONTRIBUTING.md
- package.json
- scripts/release.sh
- scripts/updateTurtleCliExampleRepo.sh
To automate the process of bumping `turtle-cli` version in https://github.com/expo/turtle-cli-example after each release.
- I created a CircleCI configuration in `turtle-cli-example` repository and committed it to a new branch - https://github.com/expo/turtle-cli-example/tree/updates-do-not-remove-me. The configuration contains a job (`update`) which bumps the `turtle-cli` version on `master` branch and pushes the commit to the remote repository.
- I created a script for triggering update jobs in `turtle-cli-example` and added a `after:release` hook to `realease-it` configuration which runs the script.
- I added a warning which shows up when a developer hasn't set `GITHUB_TOKEN` and `CIRCLE_API_USER_TOKEN` env variables.
> automate turtle-cli updates in the turtle-cli-example repo

- src/builders/ios/context.ts
Because of this PR - https://github.com/expo/expo-cli/pull/720/files - we need to change the workspace path for sdk >= 33 builds.
I changed the workspace path for all builds of sdk 33 and newer.
> fix ios archive builds

- CHANGELOG.md
- src/bin/setup/ios.ts
- src/bin/setup/utils/toolsDetector.ts
Fixes https://github.com/expo/turtle/issues/117
A way of detecting if a user accepted the Xcode license is to run `ibtool --version` and check whether it doesn't print any warnings/errors. I added this check to the setup phase of turtle-cli iOS builds. I also added a warning with instructions on how to fix the issue.
> add xcode license check

- CHANGELOG.md
- src/bin/utils/builder.ts
Fixes https://github.com/expo/turtle/issues/122
I fixed passing `expo.android.config` object to the Android builder (we were always passing `expo.ios.config` instead).
> fix passing android config to builder

- src/builders/ios/index.ts
- src/jobManager.ts
- src/server.ts
- src/validator.ts
https://github.com/expo/universe/issues/3739
We don't mark a build job as errored in the database when the job JSON is invalid. I added this behavior and also added a more detailed log in that case.
> handle invalid build jobs in better way

- CHANGELOG.md
- src/bin/setup/android/index.ts
Fixes #154, #153 and many other issues.
I added a check for the installed Java version. Android apps have to be built with Java 8.
> [turtle-cli] enforce java 8

- CHANGELOG.md
- package.json
- shellTarballs/android/sdk35
- yarn.lock
Required for https://github.com/expo/expo/pull/5924 to work.
Upgraded XDL with [appropriate changes](https://github.com/expo/expo-cli/pull/1118).
> Upgrade XDL to support Facebook autoinit-disabling features

- src/builders/utils/ios/shellAppBuilder.ts
- when we bumped the XDL version, it included some changes that causes the manifest not to be read when we write the `entitlements` file
- this is causing a lot of problems, because people are unable to submit their apps to the AppStore without the proper values in the `entitlements` file.
- The check [here](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/IosNSBundle.ts#L161) is returning `false` and preventing us from reading in the manifest.
- This is caused by this check [here](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/StandaloneContext.ts#L23) because turtle doesn't currently pass in the new parameter `shellAppSdkVersion` to the `IosShellAppBuilder`
https://twitter.com/defquan/status/1195076300056084480 …
> add shellAppSdkVersion param to iosShellAppBuilder

- CHANGELOG.md
- src/bin/utils/builder.ts
Reported internally (cc @paulmichalak)
I changed the logic for making `experienceName` if the `expo.owner` field is defined.
> Fix expo.owner not being used

- CHANGELOG.md
- shellTarballs/ios/sdk36
Fixes https://github.com/expo/expo/issues/6524
Updating iOS shell tarball for SDK36.
> Add missing RCTAssetsLibraryRequestHandler to iOS tarball for SDK36

- CHANGELOG.md
- package.json
- yarn.lock
CA certs have expired on previous versions of traveling fastlane and `https` requests made with it will fail (for example, see [this](https://staging.expo.io/builds/a63ef90c-9d60-46a8-9c04-f92560924c56))
> bump traveling-fastlane to 1.11.4

- Dockerfile
- docker-base/Dockerfile
Every first build on a new builder requires downloading the appropriate Gradle version.
I preinstalled Gradle 4.10.2 (for SDK <36) and 5.6.3 (for SDK 36) in the builder container.
> preinstall gradle 4.10.2 and 5.6.3

- CHANGELOG.md
- shellTarballs/android/sdk37
This is a better solution for https://github.com/expo/turtle/issues/200
I removed the `jq` usage from `check-dynamic-macros-android.sh`.
I generated a new shell app from `expo/expo#sdk-37` branch and updated it here.
> [android] update sdk37 tarball so it doesn't use jq internally

- Dockerfile
- scripts/build.sh
Improve deployment speed from 1h 30 min to 45 min
- skip dependency installation inside `packages` directory
- fetch shellapps inside docker build (`ADD` is faster)
- switch from using `mv` to symlink to install yarn dependecies
> improve deployment speed for android workers

- CHANGELOG.md
- Dockerfile
- src/bin/setup/android/index.ts
The build process doesn't use any of the `devDependencies` of shell apps and installing them makes the process slower and using more memory.
Added the `--prod` flag to `yarn install` happening inside shell apps so Yarn installs only the real dependencies of the project. This omits dependencies like:
- `babel-core`, `prettier`, `eslint` — we won't transpile, analyze, prettify JS when building the project,
- `expo-cli` — we could use `expo-cli` when building the project, but we don't (`expotools` are used and they are installed in the shell app)
- `expo-yarn-workspaces` — the `--ignore-scripts` removes the need for `expo-yarn-workspaces`
I have tested these changes as part of https://github.com/expo/turtle/pull/209. I have built two apps on SDK37 and both were built successfully.
> Install only production dependencies in shell apps

- CHANGELOG.md
- package.json
- shellTarballs/android/sdk37
- yarn.lock
- `google-services.json` was being handled unintuitively, fixed with https://github.com/expo/expo-cli/pull/1897
- Expo Client's secrets were leaking in shell apps, fixed with https://github.com/expo/expo/pull/7768
- When deployed, fixes https://github.com/expo/expo/issues/7727.
XDL was modifying `google-services.json`, removing valid keys if the user doesn't provide the same, removed key in _some other place_ (see https://github.com/expo/expo/issues/7727#issuecomment-611544439). Fixed the change in XDL, upgraded to the fixed version here. Also removed secrets from the shell app.
> Remove secrets from SDK37 shell app, fix google-services.json handling

- CHANGELOG.md
- package.json
- yarn.lock
I have noticed that not only the `app` project is being built on Turtle, but all the projects. (cross-posting from https://github.com/expo/expo-cli/pull/1937)
I've scoped the Gradle command to only build/assemble the `:app` project. It should be safe to do for all SDKs, since on all SDKs the app project was called `app`.
Published an alpha version of XDL to NPM, upgraded Turtle to it, deployed to staging and ran the build. It was over a minute faster than without this change ([new](https://staging.expo.io/dashboard/sjchmiela/builds/5c386cef-e808-49d3-91d8-9ce42af77c36) vs [old](https://staging.expo.io/dashboard/sjchmiela/builds/3d36340e-6ae1-4476-91cb-07d81f1edd1e)). (cross-posting from https://github.com/expo/expo-cli/pull/1937)
> [android] Build only the app artifact and not all available libraries

- .gitignore
- Dockerfile
- k8s/android/turtle-deployment.template.yml
- redislabs_ca.pem
- src/config.ts
- src/utils/redis.ts
Part of https://github.com/expo/universe/issues/5226
The main Redis cache now requires TLS (rediss) connections. Turtle still uses non-TLS redis connections, which means it cannot connect to the Redis instance anymore.
The Redis client is now using the CA certificate if it's defined.
> configure turtle to use the redis ca certificate

- CHANGELOG.md
- src/bin/commands/build/index.ts
- src/bin/utils/builder.ts
This adds a new `--allow-non-https-public-url` which disables validation requiring that `--public-url` have a protocol of `https://`.  This allows for unpublished builds as was possible before this validation was added (see https://github.com/expo/turtle/issues/210).
I have applied the changes manually to my local node_modules and they appear to work.  I still cannot build master.
> Allow override of protocol validation in--public-url

- CHANGELOG.md
- package.json
- src/bin/commands/build/android.ts
- src/bin/utils/builder.ts
- src/builders/android.ts
- src/job.ts
- src/jobsSchemas/android.ts
- yarn.lock
Closes https://github.com/expo/turtle/issues/226
I added a new `build:android` option: `--gradle-args`. It can be used to pass custom arguments to gradle, like `--stacktrace`.
> build:android - allow for passing custom gradle args

- CHANGELOG.md
- shellTarballs/android/sdk38
See https://github.com/expo/expo/pull/9446 and https://forums.expo.io/t/google-api-level-29/41231.
Updated Android SDK38 tarball with project with updated `targetSdkVersion`.
> Update Android shell tarball for SDK38 with targetSdkVersion bumped to 29

- CHANGELOG.md
- package.json
- yarn.lock
Lands https://github.com/expo/expo-cli/pull/2547 in Turtle. This is a prerequisite for https://github.com/expo/expo/pull/10059 to be able to land (otherwise Turtle would end up with the offending block in root `build.gradle` which would fail the builds since there is no `:ReactAndroid` project in Turtle workspace).
Upgrades XDL.
> Upgrade XDL so it processes root build.gradle too

- k8s/android/turtle-deployment.template.yml
Builds started to fail with
```
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Error: ./gradlew exited with non-zero code: 1
at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
at Object.onceWrapper (events.js:418:26)
at ChildProcess.emit (events.js:311:20)
at ChildProcess.EventEmitter.emit (domain.js:482:12)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
...
at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
at …
```
> Hardcode maximum heap size

- CHANGELOG.md
- src/builders/android.ts
- src/builders/utils/unimodules.ts
Fixes https://github.com/expo/expo/issues/10569. I discussed this with @sjchmiela and we decided this was the most feasible solution.
I made `resolveNativeModules` also take a `sdkVersion` argument and if it is greater than or equal to 39.0.0 then we add the expo-notifications module.
> [android] Always add expo-notifications for SDK >= 39 projects with android.enableDangerousExperimentalLeanBuilds enabled

- CHANGELOG.md
- shellTarballs/android/sdk39
Apply https://github.com/expo/expo/pull/10807.
Fixes app crashing when using Reanimated v2.
> Fix Reanimated v2 not being configured in production mode

- CHANGELOG.md
- shellTarballs/ios/client
- shellTarballs/ios/sdk36
- shellTarballs/ios/sdk37
- shellTarballs/ios/sdk38
- shellTarballs/ios/sdk39
- src/builders/ios/index.ts
As `turtle v1` is going to use Xcode 12.1 we have to update all the iOS shellApps to be pre-build with the very Xcode version.
> [ios][shellApps] Rebuild all supported shellApps with Xcode 12.1

- CHANGELOG.md
- src/builders/ios/index.ts
Bringing back https://github.com/expo/turtle/pull/273/commits/c54455543ea90c17488081e48c76cb8cf10802a3 (https://github.com/expo/turtle/pull/273) to enable Xcode 12.1 usage.
Build using Xcode 12.1 breaks with `ibtool` error, because it fails in finding simulator-related libs for some reason, even though simulators are available on the machine. Running `xcrun simctl list` before Xcode build seems to fix the problem with finding the libraries.
> [iOS] Run 'xcrun simctl list' before build to prevent ibtool crash

- CHANGELOG.md
- shellTarballs/ios/client
- shellTarballs/ios/sdk36
- shellTarballs/ios/sdk37
- shellTarballs/ios/sdk38
- shellTarballs/ios/sdk39
- Accommodate https://github.com/expo/expo/pull/11052 in all shellApps.
- Rebuild iOS shellApps using Xcode 12.1.
https://app.circleci.com/pipelines/github/expo/expo/23938/workflows/6313d313-0862-4f91-a797-d2b88706f9ee/jobs/158924
https://app.circleci.com/pipelines/github/expo/expo/23934/workflows/de1540f6-877a-41db-92b7-cbd1636fe165/jobs/158887
https://app.circleci.com/pipelines/github/expo/expo/23930/workflows/4b3f770f-e8a3-405f-a1b9-6319a97825e2/jobs/158862
https://github.com/expo/expo/actions/runs/368338037
> [iOS] Rebuild shell tarballs

- CHANGELOG.md
- scripts/release.sh
- scripts/releaseBeta.sh
- scripts/updateTurtleCliExampleRepo.sh
- [] I've ensured the unit and smoke tests are still passing - either by running `yarn test:unit` and `yarn test:smoke:[ios|android]` or by checking the appropriate CircleCI builds' statuses.
I went to deploy a release from a relatively fresh machine and ended up in this state:
```
⠙ yarn release:update:turtle-cli-example
$ ./scripts/updateTurtleCliExampleRepo.sh
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ yarn release:update:turtle-cli-example
ERROR ./scripts/updateTurtleCliExampleRepo.sh: line 17: jq: command not found
error Command failed with exit code 127.
Rolling back changes...
error Command failed with exit code 1.
```
It was pretty unclear how I could recover from this, and so it's best to avoid getting into this state if possible.
I …
> Verify jq installation in scripts

- CHANGELOG.md
- src/builders/ios/index.ts
The use of sudo does not appear to be necessary to execute 'xcrun simctl list'.
In our build environment the user running turtle does not have elevated permissions. We performed all the setup steps using an administrative account, but have a dedicated, limited user account for the actual CI builds we perform using Jenkins.
We had no troubles with our build prior to release 0.19.1, which introduced a fix for building with Xcode 12.1. Following this release, our builds started failing. Perhaps it is just our environment, but we have no issues executing xcrun without elevated permissions. At this point we are building with Xcode 12.2 successfully using this change.
Removed the use of 'sudo' to run 'xcrun simctl list' as introduced by #279.
We tested this patch in place by updating the …
> Fixed the iOS build when user does not have elevated permissions

- shellTarballs/android/sdk40
This version contains [PR #11399](https://github.com/expo/expo/pull/11399) to fix android background permissions check for Android <9.
- Includes [PR #11399](https://github.com/expo/expo/pull/11399)
- Backported [to `sdk-40` branch](https://github.com/expo/expo/commit/d07eaeb668cf1132d7e8e49da2ccb0c449a1a81f)
- Generated [from this workflow](https://github.com/expo/expo/runs/1597378742)
> [android] Upgrade to client 2.18.5 with background permission fix

- package.json
- yarn.lock
The client app was renamed to expo go and the regexp responsible for substituting that name for standalone builds was only looking for `Expo`.
> [android] remove Go suffix from android app name

- k8s/android/turtle-deployment.template.yml
https://linear.app/expo/issue/ENG-895/investigate-occasionally-failing-builds-on-turtle-android
Increase memory limits on k8s and for JVM
For k8s i set `request` to 9GB and limit to 10GB, because the host has 30 GB and I want to make sure that 3 pods could  be scheduled on host
> increase android worker memory and cpu limits

- package.json
- yarn.lock
update node-forge to 0.10.0
closes #324 
- check with yarn why which packages are using older version of node-forge
- remove from yarn.lock entries referring to node-forge, google-p12-pem, selfsigned
- run yarn install
```
yarn why node-forge
yarn why v1.22.0
[1/4] Why do we have the module "node-forge"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "node-forge@0.10.0"
info Reasons this module exists
- "@expo#xdl" depends on it
- Hoisted from "@expo#xdl#node-forge"
- Hoisted from "@expo#xdl#webpack-dev-server#selfsigned#node-forge"
- Hoisted from "@google-cloud#logging-bunyan#google-auth-library#gtoken#google-p12-pem#node-forge"
info Disk size without dependencies: "1.77MB"
info Disk size with unique dependencies: "1.77MB" …
```
> update to node-forge 0.10.0

- CHANGELOG.md
- src/logger/index.ts
- src/logger/streams/index.ts
- src/logger/streams/s3.ts
https://sentry.io/organizations/expoio/issues/1592626714/?project=1215772&query=is%3Aunresolved
This crash occurred when this other crash occurred: https://sentry.io/organizations/expoio/issues/1590618351/?project=1215772&query=is%3Aunresolved
> [logger] Fix s3 logger stream close crash

- package.json
- yarn.lock
Updating XDL version which adds Media Library permission for Android 10+: 
https://github.com/expo/xdl/commit/b9302db26c8d5005666e43ad4ac14b8c896c1a49
> update xdl to v59.1.5

- src/builders/android.ts
google bintray went down and returns 502 errors, which immediately is causing gradle scripts to fail. Redirecting it to localhost will force gradle to check other registries before erroring which should work for most if not all supported sdks
> redirect google bintray url to localhost

- k8s/android/turtle-deployment.template.yml
- package.json
- yarn.lock
Update aws SDK to the latest version
change how sqs region is specified (`aws.west2` is not supported anymore)
ios part was changed directly in the turtle-deploy repo
> update aws sdk

- shellTarballs/android/sdk40
- shellTarballs/android/sdk41
- shellTarballs/android/sdk42
- shellTarballs/android/sdk43
- src/builders/android.ts
fix android gradle build errors for dl.bintray.com and google.bintray.com return http 502.
apply https://github.com/expo/expo/pull/15349 to sdk 40-43 shell apps.
i did not verify the new shell apps yet, will do it after deploying to staging.
do we need to backport the fix to older sdks for sdk36 - sdk39?
> [android] Update android shell tarballs for bintray error fix

- CHANGELOG.md
- src/builders/utils/unimodules.ts
Currently on SDK 44 beta we're not including expo-updates in builds.
The issue appears to be that we renamed **unimodule.json** to **expo-module.config.json** and we currently resolve modules by looking for **unimodule.json** only (h/t @esamelson for spotting this).
> [builder] Resolve modules by either unimodule.json or expo-module.config.json

- CHANGELOG.md
- src/__tests__/fixtures/iosJob.json
This PR swaps out the hard coded `d1wp6m56sqw74a.cloudfront.net` cdn with `classic-assets.eascdn.net`
Replacing domains will help us gradually shift traffic away from CloudFront to Cloudflare if we wanted to. However, we make assumptions, including in shipped client code in end-user apps, about https://d1wp6m56sqw74a.cloudfront.net.
> switch cloudfront domain to classic-assets.eascdn.net

- Dockerfile
- docker-base/Dockerfile
- scripts/android/configureAndroidSdk.sh
- src/bin/setup/android/index.ts
- src/bin/setup/android/sdk.ts
- src/bin/setup/utils/common.ts
Next SDK will require jdk11
Remove requirement for jdk8 from turtle-cli
Install jdk 11 for cloud builds
Tested sdk-44 with turtle-cli
Tested on staing with all sdk from 44 to 39 (for older ones I was not able to publish the bundle on init project)
> Switch to JDK 11

- shellTarballs/android/sdk45
- n/a I've updated the [CHANGELOG](https://github.com/expo/turtle/blob/master/CHANGELOG.md) if necessary.
fix the android build errors where react-native-gradle-plugin is not found
basically the change is covered in this pr: https://github.com/expo/expo/pull/17616
> Update android sdk 45 tarball to fix build errors
