expo/turtle

- CONTRIBUTING.md
- README.md
To help users in contributing to Turtle CLI.
Added CONTRIBUTING.md and updated README.
> add CONTRIBUTING.md and update README

- Dockerfile
- scripts/cli/configureAndroidSdk.sh
- src/bin/setup/android/sdk.ts
Fixes https://github.com/expo/expo/issues/3266
> Update Android build tools

- shellTarballs/ios/sdk32
See https://github.com/expo/expo/pull/3431.
> [ios] Fix bare notifications in standalone mode on SDK32

- package.json
- shellTarballs/ios/client
- src/aws/sqs.ts
- src/bin/setup/utils/common.ts
- src/builders/BuildError.ts
- src/builders/android.ts
- src/builders/ios/archive.ts
- src/builders/ios/context.ts
- src/builders/ios/index.ts
- src/builders/utils/android/credentials.ts
- src/builders/utils/android/workingdir.ts
- src/builders/utils/image.ts
- src/builders/utils/ios/adhocBuild.ts
- src/builders/utils/ios/shellAppBuilder.ts
- src/builders/utils/ios/workingdir.ts
- src/builders/utils/workingdir.ts
- src/config.ts
- src/constants/index.ts
- src/constants/ios.ts
- src/job.ts
- src/jobManager.ts
- src/jobsSchemas/ios.ts
- yarn.lock
Adds support for Expo Client builds.
> [ios] add support for expo client builds

- src/builders/android.ts
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
How did you build this feature or fix this bug and why?
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.
> Sending manifest when building Android shell app

- src/builders/android.ts
- src/builders/ios/index.ts
- src/builders/utils/version.ts
Fixes #23 
already implemented in ios builder
set old version in app.json and run build
> [android-builder] check if sdk is supported

- CHANGELOG.md
- src/bin/commands/build/index.ts
- src/bin/utils/builder.ts
- src/bin/utils/project.ts
> add config param

- package.json
- yarn.lock
> Fix lint errors before commit

- package.json
- scripts/setWorkingdirMode.sh
- src/builders/android.ts
- src/builders/utils/unimodules.ts
- yarn.lock
Support for custom builds on android #7
> android custom builds

- .circleci/config.yml
> install curl and sed

- CHANGELOG.md
- package.json
- src/config.ts
- src/jobManager.ts
- src/utils/redis.ts
- yarn.lock
Wait for logs upload before restarting pod.
Change build timeout to 15 minutes
Add timeout for asset download (20 seconds per file) - xdl
> upload logs to s3 on timeout

- package.json
- src/scripts/setReplicaCount.ts
- src/utils/metadata.ts
Needed for https://github.com/expo/universe/issues/3529
Added a script and a few commands in package.json.
I tested the script locally.
> add script for for setting builder replica count in redis

- CHANGELOG.md
- package.json
- src/bin/index.ts
- src/bin/setup/android/index.ts
- src/bin/setup/android/sdk.ts
- src/bin/setup/ios.ts
- src/bin/setup/utils/common.ts
- src/bin/utils/user.ts
- src/builders/android.ts
- src/builders/ios/archive.ts
- src/builders/ios/context.ts
- src/builders/utils/android/credentials.ts
- src/builders/utils/android/workingdir.ts
- src/builders/utils/ios/adhocBuild.ts
- src/builders/utils/ios/keychain.ts
- src/builders/utils/ios/shellAppBuilder.ts
- src/builders/utils/ios/workingdir.ts
- src/builders/utils/version.ts
- src/server.ts
- src/types/declarations.d.ts
- yarn.lock
> rename xdl imports to @expo/xdl

- shellTarballs/android/sdk32
…
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
How did you build this feature or fix this bug and why?
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.
> [android] Update shell tarball for SDK32 with proper underlying native RN libraries

- CHANGELOG.md
- package.json
- src/bin/commands/build/android.ts
- src/bin/commands/build/ios.ts
- src/builders/android.ts
- src/builders/ios/context.ts
- src/builders/ios/index.ts
- src/builders/utils/ios/shellAppBuilder.ts
- src/builders/utils/ios/workingdir.ts
- src/builders/utils/workingdir.ts
- src/constants/index.ts
- src/constants/ios.ts
- src/job.ts
- src/jobsSchemas/ios.ts
- yarn.lock
xdl needs to be bumped before merging
https://github.com/expo/expo-cli/pull/678
> support android app bundles

- CHANGELOG.md
- scripts/setWorkingdirMode.sh
- src/bin/setup/android/index.ts
Fixes https://github.com/expo/turtle/issues/81.
> Add support for universe-package.json-less shell apps everywhere

- CHANGELOG.md
- Dockerfile
- scripts/android/supervisordEventListener.sh
- supervisord.conf
- restart pod only if there are at least 5 failures in 10 minutes
> add supervisord

- CHANGELOG.md
- shellTarballs/android/sdk33
> [android] Update SDK33 tarball to update Lottie dependency

- package.json
- yarn.lock
I'm hoping this helps isolate the ETIMEDOUT crashes.
> xdl: 54.1.4 -> 55.0.0

- src/builders/utils/ios/adhocBuild.ts
- src/jobsSchemas/ios.ts
i forgot to change the schema in `ios.ts` from https://github.com/expo/turtle/pull/88
> schema change

- CHANGELOG.md
- shellTarballs/android/sdk34
- shellTarballs/ios/sdk34
> @bbarthec/sdk34 publish tarballs

- CHANGELOG.md
- shellTarballs/ios/client
- shellTarballs/ios/sdk34
> [sdk34] Add shell tarballs for iOS

- CHANGELOG.md
- src/builders/android.ts
- src/builders/utils/unimodules.ts
Some of the modules are large or are breaking privacy policy, so they can't be included automatically everywhere
add module only if explicitly added in package.json
> require explicit opt in for certain unimodules

- CHANGELOG.md
- shellTarballs/android/sdk34
- shellTarballs/ios/sdk34
Update Android and iOS tarballs
> Update SDK34 Android tarball

- CHANGELOG.md
- package.json
- shellTarballs/ios/client
- shellTarballs/ios/sdk34
- yarn.lock
> Support for GoogleService-Info.plist (>=34.0.0)

- CHANGELOG.md
- shellTarballs/android/sdk34
See https://github.com/expo/expo/pull/5668
> [expo-branch] Change package of vendored expo-branch

- shellTarballs/ios/client
update the client shell tarball to unblock the ppl here: https://github.com/expo/expo/issues/5537
> update client shell tarball

- shellTarballs/android/sdk36
- shellTarballs/ios/client
- shellTarballs/ios/sdk36
https://github.com/expo/expo/issues/6264
> [ios][android] add SDK 36 tarballs

- Dockerfile
- docker-base/Dockerfile
- scripts/android/buildAndPushAndroidBaseImage.sh
Fixes https://github.com/expo/turtle/issues/176
> install jq on android builder

- CHANGELOG.md
- shellTarballs/ios/client
- shellTarballs/ios/sdk37
Part of https://github.com/expo/expo/issues/7173
> [ios][sdk37] Add SDK 37 shell app tarball

- CHANGELOG.md
- shellTarballs/android/sdk37
> [android][sdk37] add SDK 37 shell tarball

- src/jobManager.ts
- src/metrics/buildersConfig.ts
- src/utils/priorities.ts
Part of https://github.com/expo/universe/issues/4697
I added `turtleMode` to the `in-progress` message that we send to www.
> include turtle mode in in-progress message

- CHANGELOG.md
- package.json
- shellTarballs/android/sdk37
- yarn.lock
See https://github.com/expo/expo-cli/pull/1933.
Updates XDL so it includes change introduced in https://github.com/expo/expo-cli/pull/1933.
> Update XDL to remove check-dynamic-macros call

- src/builders/android.ts
Generates smaller apk by loading only necessary modules.
> enable lean builds

- CHANGELOG.md
- shellTarballs/ios/client
- shellTarballs/ios/sdk38
> [ios] Add shell tarballs for SDK38

- CHANGELOG.md
- shellTarballs/android/sdk38
> [android] add SDK 38 shell tarball

- CHANGELOG.md
- package.json
- src/__smoke__/smoke.test.ts
- src/aws/cloudwatch/index.ts
- src/aws/cloudwatch/statistics.ts
- src/bin/utils/builder.ts
- src/bin/utils/project.ts
- yarn.lock
closes #236 
- Upgraded typescript(some problems with @expo/config types and support for optional chaining `.?`)
- I tested by starting build command and logging prepared job, I didn't run full builds.
> use @expo/config to read project config

- src/jobManager.ts
https://github.com/expo/universe/pull/5561
I added some extra data to the `finished` and `errored` messages, namely `logUrl`, `logFormat` and `turtleMode`.
> send logs url with finished and errored messages

- CHANGELOG.md
- Dockerfile
- docker-base/Dockerfile
> [docker-base] add gradle 6.2 and set ANDROID_NDK_HOME

- CHANGELOG.md
- shellTarballs/android/sdk39
> [android] add SDK 39 tarball

- shellTarballs/ios/client
- shellTarballs/ios/sdk39
> Add SDK39 iOS tarballs

- .circleci/config.yml
> update ios smoke tests recordings

- shellTarballs/android/sdk39
- shellTarballs/android/sdk40
- shellTarballs/android/sdk41
- shellTarballs/android/sdk42
Here are the tarballs created which include the [workaround described here](https://github.com/expo/expo/issues/14248).
- SDK 39 - [action](https://github.com/expo/expo/runs/3557780082) - `s3://exp-artifacts/android-shell-builder-3fe600781956ce0823143d747a51afec5f9afe4f.tar.gz`
- SDK 40 - [action](https://github.com/expo/expo/runs/3557795804) - `s3://exp-artifacts/android-shell-builder-b111c38c47a05d1c340c69e8744fe0832b05634b.tar.gz`
- SDK 41 - [action](https://github.com/expo/expo/runs/3557798267) - `s3://exp-artifacts/android-shell-builder-ee6c4df8486ae4995e50e4d398ba0ef41a097cfe.tar.gz`
- SDK 42 - [action](https://github.com/expo/expo/runs/3557801264) - `s3://exp-artifacts/android-shell-builder-adb2b5f283e35abf75ef473f334b97fef67815bd.tar.gz`
> Update tarballs for Android location workaround

- CHANGELOG.md
- shellTarballs/android/sdk42
> Update tarball to fix local assets on SDK 42

- Dockerfile
> remove workspaces from shellapp

- CHANGELOG.md
- shellTarballs/android/sdk43
- shellTarballs/ios/sdk43
> [ios][android] update SDK 43 tarballs with expo-updates fix

- CHANGELOG.md
- shellTarballs/android/sdk43
> [android] update sdk 43 tarball

- CHANGELOG.md
- shellTarballs/ios/sdk43
> [ios] update SDK 43 tarball with expo-updates fix

- shellTarballs/android/sdk44
- shellTarballs/ios/sdk44
update sdk 44 tarballs mainly for react-native-gesture-handler 2.1.0 updates
> Update android and ios shell tarballs for sdk 44 rc

- Dockerfile
- docker-base/Dockerfile
- package.json
> update to node 14.17.3

- CHANGELOG.md
- package.json
- shellTarballs/android/sdk45
- shellTarballs/android/sdk46
- shellTarballs/ios/sdk46
- yarn.lock
Add SDK 46 support
Add SDK 46 shell tarballs
> add sdk 46 support
